/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["list_files_api_v1_projects__project_id__files_get"];
        put?: never;
        /** Upload File */
        post: operations["upload_file_api_v1_projects__project_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File */
        get: operations["get_file_api_v1_projects__project_id__files__file_id__get"];
        /** Update File */
        put: operations["update_file_api_v1_projects__project_id__files__file_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/detectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detectors */
        get: operations["detectors_api_v1_detectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rule-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rule Packs */
        get: operations["rule_packs_api_v1_rule_packs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_projects__project_id__runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_projects__project_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_v1_runs__run_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/alarms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alarms */
        get: operations["alarms_api_v1_runs__run_id__alarms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/alarms/{alarm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alarm */
        get: operations["alarm_api_v1_runs__run_id__alarms__alarm_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnostics */
        get: operations["diagnostics_api_v1_runs__run_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cfg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cfg */
        get: operations["cfg_api_v1_runs__run_id__cfg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** States */
        get: operations["states_api_v1_runs__run_id__states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/ir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ir */
        get: operations["ir_api_v1_runs__run_id__ir_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace */
        get: operations["trace_api_v1_runs__run_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evaluations */
        get: operations["list_evaluations_api_v1_projects__project_id__evaluations_get"];
        put?: never;
        /** Create Evaluation */
        post: operations["create_evaluation_api_v1_projects__project_id__evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation */
        get: operations["get_evaluation_api_v1_evaluations__evaluation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/{evaluation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Evaluation */
        post: operations["cancel_evaluation_api_v1_evaluations__evaluation_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/{evaluation_id}/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cases */
        get: operations["cases_api_v1_evaluations__evaluation_id__cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/{evaluation_id}/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matrix */
        get: operations["matrix_api_v1_evaluations__evaluation_id__matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlarmOut */
        AlarmOut: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /** Alarm Key */
            alarm_key: string;
            /** Detector Id */
            detector_id: string;
            /** Detector Version */
            detector_version: string;
            /** Rule Pack Id */
            rule_pack_id: string;
            /** Rule Pack Version */
            rule_pack_version: string;
            /** Cwe Id */
            cwe_id: string;
            /** Family */
            family?: string | null;
            /** Violation Kind */
            violation_kind: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "definite" | "possible";
            /** Function Name */
            function_name?: string | null;
            /** Block Id */
            block_id?: string | null;
            /** Instruction Id */
            instruction_id?: string | null;
            /** Instruction Text */
            instruction_text?: string | null;
            /** Source File Id */
            source_file_id?: string | null;
            /** Source Line */
            source_line?: number | null;
            /** Memory Object Id */
            memory_object_id: string;
            /** Object Name */
            object_name?: string | null;
            object_size: components["schemas"]["Interval"];
            offset: components["schemas"]["Interval"];
            /** Access Size Bytes */
            access_size_bytes: number;
            /** Safe Condition */
            safe_condition: string;
            /** Message */
            message: string;
            /** Reason */
            reason: string[];
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
        };
        /** Body_upload_file_api_v1_projects__project_id__files_post */
        Body_upload_file_api_v1_projects__project_id__files_post: {
            /** File */
            file: string;
            /** Path */
            path?: string | null;
        };
        /** DetectorDescriptor */
        DetectorDescriptor: {
            /** Id */
            id: string;
            /** Version */
            version: string;
            /** Name */
            name: string;
            /** Supported Cwes */
            supported_cwes: string[];
            /** Enabled */
            enabled: boolean;
        };
        /** DiagnosticOut */
        DiagnosticOut: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /** Diagnostic Id */
            diagnostic_id?: string | null;
            /** Code */
            code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "unknown_effect" | "unsupported" | "error";
            /** Message */
            message: string;
            /** Location */
            location?: {
                [key: string]: unknown;
            } | null;
            /** Impact */
            impact: string;
            /** Function Name */
            function_name?: string | null;
            /** Block Id */
            block_id?: string | null;
            /** Instruction Id */
            instruction_id?: string | null;
            /** Source File Id */
            source_file_id?: string | null;
            /** Source Line */
            source_line?: number | null;
        };
        /** EvaluationCaseOut */
        EvaluationCaseOut: {
            /** Id */
            id: string;
            /** Evaluation Id */
            evaluation_id: string;
            /** Case Name */
            case_name: string;
            /** Cwe Id */
            cwe_id: string | null;
            /** Family */
            family: string | null;
            /** Bad Run Id */
            bad_run_id: string | null;
            /** Good Run Id */
            good_run_id: string | null;
            /** Bad Outcome */
            bad_outcome: string;
            /** Good Outcome */
            good_outcome: string;
            /** Classification */
            classification: string | null;
        };
        /** EvaluationCreate */
        EvaluationCreate: {
            /** Dataset Name */
            dataset_name: string;
            /**
             * Dataset Version
             * @default 1
             */
            dataset_version: string;
            /** Detector Id */
            detector_id: string;
            /** Rule Pack Id */
            rule_pack_id: string;
            /** Filter */
            filter?: {
                [key: string]: unknown;
            };
            /** Cases */
            cases?: {
                [key: string]: unknown;
            }[];
            /** Manifest Path */
            manifest_path?: string | null;
            /** Max Cases */
            max_cases?: number | null;
        };
        /** EvaluationOut */
        EvaluationOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Dataset Name */
            dataset_name: string;
            /** Dataset Version */
            dataset_version: string;
            /** Detector Id */
            detector_id: string;
            /** Detector Version */
            detector_version: string;
            /** Rule Pack Id */
            rule_pack_id: string;
            /** Rule Pack Version */
            rule_pack_version: string;
            /** Status */
            status: string;
            /** Filter */
            filter: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: unknown;
            /** Started At */
            started_at?: unknown;
            /** Finished At */
            finished_at?: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Interval */
        Interval: {
            /** Lower */
            lower?: number | null;
            /** Upper */
            upper?: number | null;
            /**
             * Is Bottom
             * @default false
             */
            is_bottom: boolean;
        };
        /** MatrixOut */
        MatrixOut: {
            /** Detector Id */
            detector_id: string;
            /** Rule Pack Id */
            rule_pack_id: string;
            /** Cwe Id */
            cwe_id?: string | null;
            /** Family */
            family?: string | null;
            /** Correct */
            correct: number;
            /** False Positive */
            false_positive: number;
            /** False Negative */
            false_negative: number;
            /** Inverted */
            inverted: number;
            /** Unsupported */
            unsupported: number;
            /** Error */
            error: number;
            /** Total */
            total: number;
            /** Bad Recall */
            bad_recall?: number | null;
            /** Good Specificity */
            good_specificity?: number | null;
            /** File Accuracy */
            file_accuracy?: number | null;
        };
        /** Page[AlarmOut] */
        Page_AlarmOut_: {
            /** Items */
            items: components["schemas"]["AlarmOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[DetectorDescriptor] */
        Page_DetectorDescriptor_: {
            /** Items */
            items: components["schemas"]["DetectorDescriptor"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[DiagnosticOut] */
        Page_DiagnosticOut_: {
            /** Items */
            items: components["schemas"]["DiagnosticOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[EvaluationCaseOut] */
        Page_EvaluationCaseOut_: {
            /** Items */
            items: components["schemas"]["EvaluationCaseOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[EvaluationOut] */
        Page_EvaluationOut_: {
            /** Items */
            items: components["schemas"]["EvaluationOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[ProjectOut] */
        Page_ProjectOut_: {
            /** Items */
            items: components["schemas"]["ProjectOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[RulePackDescriptor] */
        Page_RulePackDescriptor_: {
            /** Items */
            items: components["schemas"]["RulePackDescriptor"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[RunOut] */
        Page_RunOut_: {
            /** Items */
            items: components["schemas"]["RunOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[SourceFileOut] */
        Page_SourceFileOut_: {
            /** Items */
            items: components["schemas"]["SourceFileOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Debug Mode
             * @default false
             */
            debug_mode: boolean;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Debug Mode */
            debug_mode: boolean;
            /** Created At */
            created_at: unknown;
        };
        /** RulePackDescriptor */
        RulePackDescriptor: {
            /** Id */
            id: string;
            /** Detector Id */
            detector_id: string;
            /** Version */
            version: string;
            /** Name */
            name: string;
            /** Supported Cwes */
            supported_cwes: string[];
            /** Supported Families */
            supported_families: string[];
            /** Supported Violation Kinds */
            supported_violation_kinds: string[];
        };
        /** RunCreate */
        RunCreate: {
            /** File Ids */
            file_ids?: string[];
            /** Detector Id */
            detector_id: string;
            /** Rule Pack Id */
            rule_pack_id: string;
            /** Detector Version */
            detector_version?: string | null;
            /** Rule Pack Version */
            rule_pack_version?: string | null;
            /**
             * Variant
             * @default single
             */
            variant: string;
            /**
             * Mode
             * @default normal
             * @enum {string}
             */
            mode: "normal" | "trace";
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Cwe Id */
            cwe_id?: string | null;
            /** Family */
            family?: string | null;
            /** Violation Kind */
            violation_kind?: string | null;
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Status */
            status: string;
            /** Detector Id */
            detector_id: string;
            /** Detector Version */
            detector_version: string;
            /** Rule Pack Id */
            rule_pack_id: string;
            /** Rule Pack Version */
            rule_pack_version: string;
            /** Analyzer Version */
            analyzer_version: string;
            /** Result Schema Version */
            result_schema_version: string;
            /** File Ids */
            file_ids: string[];
            /** Variant */
            variant: string;
            /** Mode */
            mode: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Progress */
            progress: number;
            /** Error Message */
            error_message: string | null;
            /** Created At */
            created_at: unknown;
            /** Started At */
            started_at?: unknown;
            /** Finished At */
            finished_at?: unknown;
        };
        /** SourceFileDetailOut */
        SourceFileDetailOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Path */
            path: string;
            /** Language */
            language: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Created At */
            created_at: unknown;
            /** Content */
            content: string;
        };
        /** SourceFileOut */
        SourceFileOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Path */
            path: string;
            /** Language */
            language: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Created At */
            created_at: unknown;
        };
        /** SourceFileUpdate */
        SourceFileUpdate: {
            /** Content */
            content: string;
        };
        /** SummaryOut */
        SummaryOut: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Detector Id */
            detector_id: string;
            /** Rule Pack Id */
            rule_pack_id: string;
            /** Alarm Count */
            alarm_count: number;
            /** Definite Count */
            definite_count: number;
            /** Possible Count */
            possible_count: number;
            /** Diagnostic Count */
            diagnostic_count: number;
            /** Unsupported Count */
            unsupported_count: number;
            /** Error Count */
            error_count: number;
            /** Duration Ms */
            duration_ms: number | null;
            /** Functions Analyzed */
            functions_analyzed: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProjectOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_api_v1_projects__project_id__files_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SourceFileOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_v1_projects__project_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_v1_projects__project_id__files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_v1_projects__project_id__files__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFileDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_file_api_v1_projects__project_id__files__file_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceFileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFileDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detectors_api_v1_detectors_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DetectorDescriptor_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rule_packs_api_v1_rule_packs_get: {
        parameters: {
            query?: {
                detector_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RulePackDescriptor_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_projects__project_id__runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RunOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_projects__project_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_v1_runs__run_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alarms_api_v1_runs__run_id__alarms_get: {
        parameters: {
            query?: {
                detector_id?: string | null;
                rule_pack_id?: string | null;
                cwe_id?: string | null;
                family?: string | null;
                violation_kind?: string | null;
                severity?: string | null;
                function?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AlarmOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alarm_api_v1_runs__run_id__alarms__alarm_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                alarm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlarmOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnostics_api_v1_runs__run_id__diagnostics_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                severity?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DiagnosticOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cfg_api_v1_runs__run_id__cfg_get: {
        parameters: {
            query?: {
                function?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    states_api_v1_runs__run_id__states_get: {
        parameters: {
            query?: {
                function?: string | null;
                block_id?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ir_api_v1_runs__run_id__ir_get: {
        parameters: {
            query?: {
                function?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_api_v1_runs__run_id__trace_get: {
        parameters: {
            query?: {
                function?: string | null;
                block_id?: string | null;
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluations_api_v1_projects__project_id__evaluations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EvaluationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_evaluation_api_v1_projects__project_id__evaluations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_api_v1_evaluations__evaluation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_evaluation_api_v1_evaluations__evaluation_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cases_api_v1_evaluations__evaluation_id__cases_get: {
        parameters: {
            query?: {
                detector_id?: string | null;
                rule_pack_id?: string | null;
                cwe_id?: string | null;
                family?: string | null;
                violation_kind?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EvaluationCaseOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matrix_api_v1_evaluations__evaluation_id__matrix_get: {
        parameters: {
            query?: {
                cwe_id?: string | null;
                family?: string | null;
            };
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatrixOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
